import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { css } from '@root/styled-system/css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={css({
        fontSize: 'base',
        fontWeight: 'regular',
        bg: 'bg',
        color: 'color',
      })}
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
