name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  check-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Clean install dependencies
        run: npm clean-install

      - name: Check formatting for project
        run: npm run format-check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Clean install dependencies
        run: npm clean-install

      - name: Build project
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Clean install dependencies
        run: npm clean-install

      - name: Test project
        run: npm run test:ci

  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          prnumber: ${{ steps.findPr.outputs.number }}
